# @baseUrl = https://geeder.patrickpang.me
@baseUrl = http://localhost:8000

###
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "username": "dudu",
  "password": "{{$dotenv DUMMY_PASSWORD}}"
}
