// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $_middleware from "./routes/_middleware.ts";
import * as $admin from "./routes/admin.tsx";
import * as $auth_login from "./routes/auth/login.ts";
import * as $cards_create from "./routes/cards/create.ts";
import * as $cards_delete from "./routes/cards/delete.ts";
import * as $cards_pull from "./routes/cards/pull.ts";
import * as $index from "./routes/index.tsx";
import * as $llm_ask from "./routes/llm/ask.ts";
import * as $login from "./routes/login.tsx";
import * as $logout from "./routes/logout.tsx";
import * as $CardsEditor from "./islands/CardsEditor.tsx";
import * as $ExcerptInput from "./islands/ExcerptInput.tsx";
import * as $LoginForm from "./islands/LoginForm.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/_middleware.ts": $_middleware,
    "./routes/admin.tsx": $admin,
    "./routes/auth/login.ts": $auth_login,
    "./routes/cards/create.ts": $cards_create,
    "./routes/cards/delete.ts": $cards_delete,
    "./routes/cards/pull.ts": $cards_pull,
    "./routes/index.tsx": $index,
    "./routes/llm/ask.ts": $llm_ask,
    "./routes/login.tsx": $login,
    "./routes/logout.tsx": $logout,
  },
  islands: {
    "./islands/CardsEditor.tsx": $CardsEditor,
    "./islands/ExcerptInput.tsx": $ExcerptInput,
    "./islands/LoginForm.tsx": $LoginForm,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
