name: Nuitka

on:
  push:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['macos-latest']

    steps:
    - uses: actions/checkout@v4

    - name: ccache
      uses: hendrikmuhs/ccache-action@v1.2

    - uses: actions/setup-python@v5
      with:
        python-version: 3.11
    - run: pip install -r requirements.txt Nuitka==2.2 imageio==2.34.1

    - run: python -m nuitka --standalone --macos-create-app-bundle --macos-app-icon=static/android-chrome-512x512.png --include-data-dir=static=static --include-data-files=wrapper=. --output-dir=dist main.py
    - run: chmod u+x main.app/Contents/MacOS/{main,wrapper}
    - run: python change_entry_point.py

    - uses: actions/upload-artifact@v4
      with:
        name: Nuitka
        path: dist/main.app
