name: PyInstaller

on:
  push:

jobs:
  pyinstaller-build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['windows-latest', 'ubuntu-latest', 'macos-latest']

    steps:
      - name: Create Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.12'
          pyinstaller_ver: '==6.6.0'
          spec: 'main.py'
          requirements: 'requirements.txt'
          upload_exe_with_name: 'geeder'
          options: --onefile, --name "Geeder", --windowed 
