name: PyInstaller

on:
  push:

jobs:
  pyinstaller-build:
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - { os: windows-latest, arch: x64 }
          - { os: ubuntu-latest, arch: x64 }
          - { os: macos-latest, arch: arm64 }

    steps:
      - name: Create Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_arch: ${{ matrix.config.arch }}
          python_ver: '3.12'
          pyinstaller_ver: '==6.6.0'
          spec: 'main.py'
          requirements: 'requirements.txt'
          upload_exe_with_name: 'geeder'
          options: --onefile, --name "Geeder", --windowed 
