// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_login from "./routes/api/login.ts";
import * as $index from "./routes/index.tsx";
import * as $llm_ask from "./routes/llm/ask.ts";
import * as $login from "./routes/login.tsx";
import * as $logout from "./routes/logout.tsx";
import * as $CardsEditor from "./islands/CardsEditor.tsx";
import * as $ExcerptInput from "./islands/ExcerptInput.tsx";
import * as $LoginForm from "./islands/LoginForm.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/api/login.ts": $api_login,
    "./routes/index.tsx": $index,
    "./routes/llm/ask.ts": $llm_ask,
    "./routes/login.tsx": $login,
    "./routes/logout.tsx": $logout,
  },
  islands: {
    "./islands/CardsEditor.tsx": $CardsEditor,
    "./islands/ExcerptInput.tsx": $ExcerptInput,
    "./islands/LoginForm.tsx": $LoginForm,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
